remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Chris's Pages"
tagline: "A place where I post and store things I do and learn."
description: ""
markdown: kramdown
